import main.Person;
import phone.AndroidPhone;
import phone.IPhone;
import phone.Mobile;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
//		System.out.println(new App().getGreeting());
//		Mobile mobile = new AndroidPhone();
//		mobile.outMessage();
		Mobile mobile = new Mobile("小灵通", "red", "12");
		Mobile iphone = new IPhone("iphone5s", "white", "12");
		Mobile android = new AndroidPhone("vivoZ5", "white", "12");
		
		Person person = new Person("syf", iphone);
		person.userPhone("111111111111111111111111111111");
	}
}
